# Indexing & Broadcasting in Numpy

![Namespace Labs](../../../labs.png)

In [1]:
import numpy as np

In [27]:
matrix = np.arange(1,17)

In [3]:
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [4]:
matrix[0]

1

In [5]:
matrix[2]

3

In [6]:
matrix[2:6]

array([3, 4, 5, 6])

In [7]:
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [8]:
matrix[12:]

array([13, 14, 15, 16])

# Indexing Two Dimensional Array

In [28]:
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [29]:
matrix.size

16

In [31]:
matrix.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [33]:
matrix = matrix.reshape(4,4)

In [34]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
matrix[0] 

array([1, 2, 3, 4])

In [14]:
matrix[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
matrix[1:3,1:3] # [startrow:endrow, startcolumn:endcolumn]

array([[ 6,  7],
       [10, 11]])

In [23]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
matrix[2:4,1:2]

array([[10],
       [14]])

In [35]:
matrix[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [36]:
matrix[2:,2:]

array([[11, 12],
       [15, 16]])

# Part 2

# Broadcasting in NumPy

In [47]:
scores = [50,60,70,30,25]

In [48]:
scores_array = np.array(scores)

In [49]:
scores_array

array([50, 60, 70, 30, 25])

In [50]:
scores_array[0:3]

array([50, 60, 70])

In [51]:
scores_array[0:3] = [20,40,90]

In [52]:
scores_array

array([20, 40, 90, 30, 25])

Happy Coding!