# NumPy for Numerical Computation

![Namespace Labs](../../../labs.png)

NumPy is an open source Python package for numerical computation in Python

## Installing NumPy

conda install numpy

or

pip install numpy

### Why use NumPy?

- faster and more compact than Python lists
- consumes less memory and is convenient to use
- Other data science packages are built on top of it

# Data Types

In [1]:
import numpy as np

In [2]:
x = np.float(1.25844) 

In [3]:
x

1.25844

In [4]:
type(x)

float

In [5]:
w = np.int(1.2222)

In [6]:
w

1

In [7]:
type(w)

int

## Ways to Create NumPy Arrays

A NumPy array is a multidimensional array-like data structure

### np.arange()

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Covert Python List to a NumPy Array

In [11]:
scores = [50,60,70,30,25,70]

In [12]:
scores_array = np.array(scores)

In [13]:
scores_array

array([50, 60, 70, 30, 25, 70])

In [14]:
type(scores_array)

numpy.ndarray

In [15]:
scores_array.ndim # the dimension of the array

1

In [16]:
scores_array.size # the number of items in the array

6

In [17]:
scores_array.dtype # the type of data in the array

dtype('int64')

In [18]:
np.unique(scores_array) # print unique items from the array

array([25, 30, 50, 60, 70])

In [19]:
scores_array

array([50, 60, 70, 30, 25, 70])

In [20]:
np.flip(scores_array) # reverse the array

array([70, 25, 30, 70, 60, 50])

In [21]:
np.sort(scores_array)

array([25, 30, 50, 60, 70, 70])

In [22]:
scores_array

array([50, 60, 70, 30, 25, 70])

In [23]:
np.clip(scores_array, 20,59)

array([50, 59, 59, 30, 25, 59])

# Part Two

### Joining Two Arrays

In [39]:
array_two = np.array([90, 26, 37, 77, 65, 55])

In [41]:
scores_array

array([50, 60, 70, 30, 25, 70])

In [40]:
np.concatenate((scores_array, array_two))

array([50, 60, 70, 30, 25, 70, 90, 26, 37, 77, 65, 55])

### np.zeros()

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### np.ones()

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
np.eye(5) # Return a 2-D array with ones on the diagonal
           # and zeros elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.linspace()

In [42]:
np.linspace(10,50,5) # Return evenly spaced numbers over a 
                      # specified interval.
                    # start,stop, num=5,

array([10., 20., 30., 40., 50.])

In [31]:
np.linspace(10,15,5)

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

In [32]:
np.random.rand(10)# Create an array of the given shape and 
                  # populate it with  random samples from
                   # a uniform distribution

array([0.82155675, 0.8434222 , 0.72446354, 0.14825197, 0.19088994,
       0.14291254, 0.20236584, 0.84807271, 0.51007889, 0.27607967])

In [33]:
np.random.rand(3,2)

array([[0.47794693, 0.5139601 ],
       [0.40653766, 0.46413972],
       [0.68135975, 0.25962136]])

In [45]:
np.random.randint(15)

1

In [44]:
np.random.randint(5,20,6)
# Return random integers from `low` (inclusive) to `high` (exclusive).

array([17,  9, 16, 11,  9, 18])

In [36]:
np.array([np.nan,6,np.nan])

array([nan,  6., nan])

# Part 3

# Checking Documentation

In [37]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [38]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : 

Happy coding!