# NumPy Operations

![Namespace Labs](../../../labs.png)

In [1]:
import numpy as np

In [2]:
matrix = np.arange(17,33)

In [3]:
matrix = matrix.reshape(4,4)

In [4]:
matrix

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [5]:
matrix.shape

(4, 4)

In [6]:
matrix.ndim

2

In [7]:
np.max(matrix)

32

In [24]:
matrix

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [8]:
np.argmax(matrix)

15

In [9]:
np.min(matrix)

17

In [10]:
np.argmin(matrix)

0

In [11]:
np.sum(matrix)

392

In [12]:
np.sqrt(matrix)

array([[4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262],
       [5.38516481, 5.47722558, 5.56776436, 5.65685425]])

In [25]:
matrix

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [13]:
matrix.transpose()

array([[17, 21, 25, 29],
       [18, 22, 26, 30],
       [19, 23, 27, 31],
       [20, 24, 28, 32]])

In [14]:
matrix

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [15]:
matrix.flatten()

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [16]:
matrix.ravel()

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [17]:
matrix2 = np.arange(1,17).reshape(4,4)

In [18]:
matrix2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
matrix + matrix2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [20]:
matrix * matrix2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

In [21]:
matrix /  matrix2

array([[17.        ,  9.        ,  6.33333333,  5.        ],
       [ 4.2       ,  3.66666667,  3.28571429,  3.        ],
       [ 2.77777778,  2.6       ,  2.45454545,  2.33333333],
       [ 2.23076923,  2.14285714,  2.06666667,  2.        ]])

In [22]:
matrix %  matrix2

array([[0, 0, 1, 0],
       [1, 4, 2, 0],
       [7, 6, 5, 4],
       [3, 2, 1, 0]])

Happy Coding!